version: '3.9'


services:

  # Postgresql
  db:
    image: postgres:14-alpine
    container_name: db_app
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5438:5432"
    networks:
      - net

  backend:
    build: .
    restart: unless-stopped
    container_name: backend_app
    command:
      - poetry run python manage.py collectstatic --noinput
      - poetry run python manage.py migrate
      - poetry run uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --workers 4
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - '8000:8000'
    env_file:
      - .env
    networks:
      - net

  # Celery
#  celery:
#    build: .
#    command: poetry run celery -A app worker -l info
#    restart: unless-stopped
#    links:
#      - app
#    depends_on:
#      - app
#    networks:
#      - net
  # Nginx
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - net


networks:
  net:
    driver: bridge