version: '3.9'


services:

  backend_app:
    build: .
    restart: unless-stopped
    container_name: backend_app
    command:
      - poetry run python manage.py collectstatic --noinput
      - poetry run python manage.py migrate
      - poetry run uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --workers 4
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - '8000:8000'
    env_file:
      - .env
    networks:
      - net

  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend_app
    networks:
      - net

volumes:
  static_volume:
  media_volume:

networks:
  net:
    driver: bridge