# Generated by Django 4.1.4 on 2023-01-11 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSendMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=90)),
                ('tel', models.CharField(max_length=20)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ture.tour')),
            ],
        ),
    ]
