# Generated by Django 4.1.4 on 2024-04-28 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60, verbose_name='Полное имя')),
                ('phone_number', models.CharField(max_length=60, verbose_name='Номер телефона')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='src.tour')),
            ],
            options={
                'verbose_name': 'Заявки на тур',
                'db_table': 'application_tour',
            },
        ),
    ]
